sudo: false

language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "6"
  - "4"

os:
  - osx
  - linux

osx_image: xcode9.2

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=gcc-7 && CXX=g++-7; fi

before_deploy:
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
  - npm run prebuild
  - tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .

deploy:
  provider: releases
  api_key:
    secure: "JJeZ8lSxwKiAyLzYDaaMg72PCHpgxgIhusIOQK6o6oogIDc/fsRpy+EI9KeRJzns6FHO7PZghRVEnMYVypUPxdqiTyT+bl1PcoK0hGeV2pXF3Cjl51+JeuCpa4ZSDIyHj0uRfiTDQSAWlveTc2DrsCFDEnIOUbU9SfjJC5Zcx6l0XDWM73cQXJA9URv1k2Xy07OiR0F5fteSkRSL0tXiVGQbeySvYHc3ADrbsDX77rX4r3tXiS12MkPhJtfssL2ZY1XagL6P0pTF6YbqW1n43Hsg3oZjmm4YUnhEvq9GENJILGyMPvpUgw/mkQgEwWrHcoy79a69n+I8kMmFV2lNJoIwTdKnvkK0AqkK+Byux3BxYH4GaNpf5YW4y90DBwgBFD6ZFN58n5CGhQEpjtLXjHDaaj8LJo/NO8kwIU28JjPU1FJcnuzWp99QV1FdSNw1Xj9nEMUxNoQ3O3UtlFT+gRpeQox4BP2OaK/WEWGXt7x/8wfN9FsT8dShNlFK05ceiAKWehNAWCZI6kB8MhDvub78JCOLPmBsMjVQjsJXoQbWES/tJLU0tmlom9JqFuT0Xg7qB+m7R7bIE08pbL9yA5xYzol7MUIQB1WInI1gwSQsTIhC0OaXns0FLiUJyXJ+af9aWqFLFys3IYzbKnMhK17GIPU7iPxnedKV5snjYdU="
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
