sudo: false

language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "6"
  - "4"

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
      env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

before_deploy:
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
  - npm run prebuild
  - tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds" .

deploy:
  provider: releases
  api_key:
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
